---
name: release
on: workflow_dispatch
jobs:
  pre-release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: license check
        run: |
          cargo install licensure
          licensure --project --check
      - name: test
        run: cargo test
      - name: bump version
        run: cargo run -- bump release
      - name: update readme
        run: |
          cargo install cargo-readme
          cargo readme > README.md
      # Building a multiline commit message
      - run: echo "release of $(cargo run -- get)" >> commitmessage.txt
      - run: echo "[no ci]" >> commitmessage.txt

      # Create a multiline string to be used by the git-auto-commit Action
      - name: set commit message
        id: commit_message_step
        run: |
          echo 'commit_message<<EOF' >> $GITHUB_OUTPUT
          cat commitmessage.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - run: rm -rf commitmessage.txt
      - name: set tag message
        id: tag_message_step
        run: |
          echo 'tag_message<<EOF' >> $GITHUB_OUTPUT
          cargo run -- get >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - uses: stefanzweifel/git-auto-commit-action@v4
        id: commit
        with:
          tagging_message: v${{ steps.tag_message_step.outputs.tag_message }}
          commit_message: ${{ steps.commit_message_step.outputs.commit_message }}
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_TOKEN }}
